'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.209
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.209.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DiscoveryServiceSoap", [Namespace]:="www.prosetech.com")>  _
    Public Class DiscoveryService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/Code/P2P/Chapter11/SecureDiscovery/DiscoveryService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.prosetech.com/GetServerDateTime", RequestNamespace:="www.prosetech.com", ResponseNamespace:="www.prosetech.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetServerDateTime() As Date
            Dim results() As Object = Me.Invoke("GetServerDateTime", New Object(-1) {})
            Return CType(results(0),Date)
        End Function
        
        '<remarks/>
        Public Function BeginGetServerDateTime(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetServerDateTime", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetServerDateTime(ByVal asyncResult As System.IAsyncResult) As Date
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Date)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.prosetech.com/RegisterNewUser", RequestNamespace:="www.prosetech.com", ResponseNamespace:="www.prosetech.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub RegisterNewUser(ByVal emailAddress As String, ByVal publicKeyXml As String)
            Me.Invoke("RegisterNewUser", New Object() {emailAddress, publicKeyXml})
        End Sub
        
        '<remarks/>
        Public Function BeginRegisterNewUser(ByVal emailAddress As String, ByVal publicKeyXml As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RegisterNewUser", New Object() {emailAddress, publicKeyXml}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndRegisterNewUser(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.prosetech.com/StartSession", RequestNamespace:="www.prosetech.com", ResponseNamespace:="www.prosetech.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function StartSession(<System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal signedLoginInfo() As Byte) As System.Guid
            Dim results() As Object = Me.Invoke("StartSession", New Object() {signedLoginInfo})
            Return CType(results(0),System.Guid)
        End Function
        
        '<remarks/>
        Public Function BeginStartSession(ByVal signedLoginInfo() As Byte, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("StartSession", New Object() {signedLoginInfo}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndStartSession(ByVal asyncResult As System.IAsyncResult) As System.Guid
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Guid)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.prosetech.com/RefreshSession", RequestNamespace:="www.prosetech.com", ResponseNamespace:="www.prosetech.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub RefreshSession(ByVal sessionID As System.Guid)
            Me.Invoke("RefreshSession", New Object() {sessionID})
        End Sub
        
        '<remarks/>
        Public Function BeginRefreshSession(ByVal sessionID As System.Guid, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RefreshSession", New Object() {sessionID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndRefreshSession(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.prosetech.com/EndSession", RequestNamespace:="www.prosetech.com", ResponseNamespace:="www.prosetech.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub EndSession(ByVal sessionID As System.Guid)
            Me.Invoke("EndSession", New Object() {sessionID})
        End Sub
        
        '<remarks/>
        Public Function BeginEndSession(ByVal sessionID As System.Guid, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("EndSession", New Object() {sessionID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndEndSession(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.prosetech.com/GetPeerInfo", RequestNamespace:="www.prosetech.com", ResponseNamespace:="www.prosetech.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPeerInfo(ByVal emailAddress As String) As PeerInfo
            Dim results() As Object = Me.Invoke("GetPeerInfo", New Object() {emailAddress})
            Return CType(results(0),PeerInfo)
        End Function
        
        '<remarks/>
        Public Function BeginGetPeerInfo(ByVal emailAddress As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPeerInfo", New Object() {emailAddress}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetPeerInfo(ByVal asyncResult As System.IAsyncResult) As PeerInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),PeerInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.prosetech.com/GetPeers", RequestNamespace:="www.prosetech.com", ResponseNamespace:="www.prosetech.com", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPeers(ByVal sessionID As System.Guid) As String()
            Dim results() As Object = Me.Invoke("GetPeers", New Object() {sessionID})
            Return CType(results(0),String())
        End Function
        
        '<remarks/>
        Public Function BeginGetPeers(ByVal sessionID As System.Guid, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetPeers", New Object() {sessionID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetPeers(ByVal asyncResult As System.IAsyncResult) As String()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String())
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.prosetech.com")>  _
    Public Class PeerInfo
        
        '<remarks/>
        Public ID As Integer
        
        '<remarks/>
        Public EmailAddress As String
        
        '<remarks/>
        Public PublicKeyXml As String
        
        '<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public ObjRef() As Byte
    End Class
End Namespace
